export enum PATH {
    LANDING_PAGE = "/home",
    LOGIN = "/login",
    REGISTRATION = "/registration",
    DASHBOARD_ADMIN = "/dashboard/admin",
    PROFILE_ADMIN = "/profiles/admin",
    PROFILE_CANDIDATE = "/profiles/candidate",
    EDIT_PROFILE_SUPER_ADMIN = "/profiles/admin/edit",
    EDIT_PROFILE_CANDIDATE = "/profiles/candidate/edit",
    CHANGE_PASSWORD_SUPER_ADMIN = "/profiles/admin/change-password",
    CHANGE_PASSWORD_SUPPORT = "/profiles/candidate/change-password",
    LIST_USER = "/users",
    ADD_USER = "/users/add",
    DETAIL_USER = "/users/detail",
    LIST_QUESTION = "/questions",
    ADD_QUESTION = "/questions/add",
    EDIT_QUESTION = "/questions/edit",
}